server/db/models/cart.js, server/db/models/guest.js, server/db/models/index.js, server/db/models/item.js, server/db/models/product.js, server/db/models/user.js
---
We created models based off of our schema
part of issue #19
=> added models

server/db/models/index.js, server/index.js
---
Added associations to our models. Issue #25
=> chore: created associations between tables

client/components/AllProducts.js, client/routes.js, client/store/allProducts.js, client/store/index.js, public/style.css, server/api/index.js, server/api/products.js, server/index.js
---
Added the all products view. Issue #6
=> All products #6

client/components/AllProducts.js, client/components/singleProduct.js, public/style.css
=> fix: alteredCSS and XTML for style purposes

client/components/Cart.js, client/routes.js
---
updated the guest_checkout route from the cart view
=> fixed: updated routes

client/routes.js
=> fix: corrected comment format

client/routes.js
=> refactor: removed async await from componentDidMount

client/routes.js
=> fix: added try catch to mapDispatch

client/components/Cart.js, public/style.css, server/db/models/user.spec.js
=> Cart css #52

server/db/models/user.spec.js
=> chore: started writing tests

client/components/guest-home.js, client/components/index.js, client/components/navbar.js, client/routes.js, public/style.css, server/db/models/product.js
=> Product model img url #31

client/components/Cart.js, client/components/guest-home.js, client/components/index.js, client/components/navbar.js, client/routes.js, public/style.css, server/db/models/user.spec.js
=> Home page #5

client/components/Cart.js, client/components/guest-home.js, client/components/index.js, client/components/navbar.js, client/routes.js, public/style.css, server/db/models/user.spec.js
=> Navbar cart #56

client/components/Cart.js, client/components/guest-home.js, client/components/index.js, client/components/navbar.js, client/routes.js, public/style.css, server/db/models/user.spec.js
=> Navbar updates #54

client/components/singleProduct.js, client/routes.js, client/store/user.js, client/store/usersCart.js, server/api/carts.js, server/api/products.js, server/auth/index.js, server/db/models/item.js
---
Issue #11 
Add to cart button now works! You can: 
- add the same item multiple times
- add different items 
- Item instances are created, or found and quantity adjusted, all based on Cart id. 
- Cart is updated in the database to reflect new total items, items array, and total cost.
Also fixed issue where sessionIDs were being recreated every time a Route rendered.
=> Add to cart feature weekend #11

client/components/navbar.js
=> chore: update logged in user navbar to display similar to guest

client/components/guest-home.js, client/components/navbar.js, client/components/user-home.js
=> Userhome #64

client/components/GuestCheckoutForm.js, client/components/guest-home.js, client/components/navbar.js, client/components/user-home.js, public/style.css
=> Guest checkout css #61

server/api/products.spec.js, server/api/users.spec.js, server/db/models/user.spec.js
=> Backend allproducts #66

client/components/AllProducts.spec.js, package-lock.json, package.json
=> Test front end all products #74

client/routes.js
=> fix: changed route order, no more 404 for cart

client/components/Cart.js
---
Disabled the checkout button in cart view if the cart is empty #86
=> disabled checkout btn if cart is empty

client/components/Cart.js, client/components/singleProduct.js, client/store/usersCart.js, server/api/carts.js
=> Cart delete item #83

package-lock.json, package.json, script/seed.js, server/api/carts.js, server/api/guests.js, server/api/users.js, server/api/verifyToken.js, server/auth/index.js, server/db/models/user.js
---
Routes are now protected! With admin access
=> Disabled checkout btn #86

client/components/Cart.js, client/store/usersCart.js, server/api/carts.js
=> chore:created edit item(increase) front end and backend

client/components/Cart.js
=> I must've deleted a curly brace by accident during code reviews.

client/components/Cart.js
=> fix: removeCart import

client/components/auth-form.js, client/routes.js, client/store/usersCart.js
=> fix: When a user logs out, a guest cart is assigned to the new session.

server/api/carts.js
=> refactor: corrected bug that cause item quantity to be less than one

server/api/carts.js, server/api/products.js
=> Admin products #105

client/components/GuestCheckoutForm.js
=> chore: guest checkout button has disabled functionality

client/store/usersCart.js, package-lock.json, package.json, script/seed.js, server/api/carts.js, server/api/products.js, server/api/users.js, server/api/verifyToken.js, server/auth/index.js, server/db/models/user.js
---
Routes have been protected!
=> fix: these routes are now protected

client/components/AllProducts.js, client/components/singleProduct.js, client/store/singleProduct.js
---
Cleared single product state when navigating away from single product view #94
=> fix: cleared single product from state

client/components/navbar.js, client/routes.js
=> fix: added a closing div that got clipped

client/components/navbar.js
=> Now the navbar shows how many items you have in your cart!

client/components/AllProducts.js, client/components/TaggedGame.js, client/components/guest-home.js, client/store/allProducts.js
---
Fixed the flash when transitioning from home page to tags
=> fix: updated the allproducts view

client/routes.js
=> fix:corrected routes for error page component

client/components/Cart.js, client/components/OrderReview.js, client/components/auth-form.js, client/components/navbar.js, client/components/user-home.js, public/style.css
=> chore: more css situations

public/style.css
=> fix: small css fix in CartView

client/components/OrderReview.js
=> fix: squashed the bug where order review form showed function
